### ISSUE TITLE
More descriptive README

### ISSUE THREAD

**Issue by hckuo2** [ultract/linux-kernel-tailoring-framework#1]
Hi,
Thank you for creating such an amazing and I would like to try it out!
However, the readme does not really informative to me. 
Would you make it more detailed (e.g., what packages are needed etc) so that I can follow exactly?

**Comment by hckuo2** [comment]
Thanks!

**Comment by hckuo2** [comment]
Also, does this tool work on Ubuntu Cosmic?

**Comment by ultract** [comment]
Hi, hckuo.
I tested this tailor tool on Ubuntu 18.04/16.04 64bit.
Also, I think I can answer easily if you ask anything in detail

**Comment by hckuo2** [comment]
Thanks. My questions:
- When should I take a snapshot of the VM?
- Can I have only 1 trace vm and 1 test vm?
- In step 1, "we need to copy the vm image into ramdisk", what vm image? trace or test?

**Comment by ultract** [comment]
Hi, my answers are :

When should I take a snapshot of the VM?
-> After you finish setting VMs(Tracing, Testing) as ubuntu-tailor/README.md file.
Can I have only 1 trace vm and 1 test vm?
-> Sorry, I can't send my vm images, because of the size of them.
In step 1, "we need to copy the vm image into ramdisk", what vm image? trace or test?
-> the vm for testing,  if you don't operate testing vms in a ramdisk, you will suffer a bottleneck issue by reverting and starting multiple vms. so, I recommend you have a workstation with a large amount of RAM.

**Comment by hckuo2** [comment]
Thank you!
